# Generated by Django 2.0.5 on 2018-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180515_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='status',
            field=models.CharField(default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
