# Generated by Django 2.0.5 on 2018-05-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180517_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='mainfest',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_company', to='core.Company'),
        ),
        migrations.AddField(
            model_name='mainfest',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='exif_datetime',
            field=models.DateField(verbose_name='exif_date'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_loc', to='core.Location'),
        ),
    ]
