# Generated by Django 2.0.5 on 2018-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180517_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfest',
            name='exif_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='exif_date'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='exif_height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='exif_height'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='exif_width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='exif_width'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='import_dir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Import Dir'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='meta_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_1'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='meta_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_2'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='meta_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='meta_3'),
        ),
    ]
