# Generated by Django 2.0.5 on 2018-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mainfest_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Header')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('region', models.CharField(blank=True, max_length=225, null=True, verbose_name='Region')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.RemoveField(
            model_name='location',
            name='section',
        ),
        migrations.AddField(
            model_name='mainfest',
            name='region',
            field=models.CharField(default=1, max_length=225, verbose_name='Region'),
            preserve_default=False,
        ),
    ]
