# Generated by Django 2.0.5 on 2018-05-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180517_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfest',
            name='region',
        ),
        migrations.AddField(
            model_name='mainfest',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_section', to='core.Section'),
        ),
    ]
