# Generated by Django 2.0.5 on 2018-05-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180517_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_loc_section', to='core.Section'),
        ),
        migrations.AlterField(
            model_name='mainfest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
