# Generated by Django 2.0.5 on 2018-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180518_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Header')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('markup', models.CharField(blank=True, max_length=225, null=True, verbose_name='Region')),
            ],
        ),
    ]
