# Generated by Django 2.0.5 on 2018-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ui',
            name='markup',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Markup'),
        ),
        migrations.AlterField(
            model_name='ui',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ui',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
