# Generated by Django 2.0.5 on 2018-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180521_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Group'),
        ),
    ]
