# Generated by Django 2.0.5 on 2018-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180524_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='datatime',
            new_name='exif_date',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='height',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='width',
        ),
        migrations.AddField(
            model_name='manifest',
            name='exif_data',
            field=models.TextField(blank=True, null=True, verbose_name='exif'),
        ),
    ]
