# Generated by Django 2.0.5 on 2018-06-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180525_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('zip', models.CharField(max_length=20, verbose_name='Zip')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes About This Customer')),
            ],
            options={
                'verbose_name_plural': 'Customers Data',
            },
        ),
    ]
